apiVersion: v1
entries:
  driver-container-base:
  - annotations:
      appVersion: '>= 1.13.0 < 1.15.0'
    apiVersion: v2
    appVersion: 1.0.0
    created: "2021-10-29T18:02:34.810585306+02:00"
    description: Driver Container Base is the base image for out-of-tree builds
    digest: 355dddf19023a7bbbe064dfaf1e44a45123876209c2c86fe7d283e35babc82ca
    icon: https://avatars.githubusercontent.com/u/55542927
    name: driver-container-base
    type: application
    urls:
    - file:///charts/deprecated/driver-container-base-0.1.0.tgz
    version: 0.1.0
generated: "2021-10-29T18:02:34.810085408+02:00"
